#!/bin/bash
SCALAMAKE_JAR="$SCALAMAKE_HOME/com.coconut_palm_software.scalamake.core-1.0.0-SNAPSHOT.jar"
TIME_JAR="$SCALAMAKE_HOME/time-2.9.0-0.2-SNAPSHOT.jar"
JODATIME_JAR="$SCALAMAKE_HOME/joda-time-2.0.jar"
JODAPRIM_JAR="$SCALAMAKE_HOME/joda-primitives-1.0.jar"
JODACONVERT_JAR="$SCALAMAKE_HOME/joda-convert-1.2.jar"

if [ -f SMakefile.scala ] && [ "./$1" != "./SMakefile.scala" ]
then
    scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" SMakefile.scala "$@"
else
    scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" "$@"
fi

