#!/bin/bash
SCALAMAKE_JAR="$SCALAMAKE_HOME/scalamake_2.11-1.0.jar"
TIME_JAR="$SCALAMAKE_HOME/time-2.9.0-0.2-SNAPSHOT.jar"
JODATIME_JAR="$SCALAMAKE_HOME/joda-time-2.0.jar"
JODAPRIM_JAR="$SCALAMAKE_HOME/joda-primitives-1.0.jar"
JODACONVERT_JAR="$SCALAMAKE_HOME/joda-convert-1.2.jar"

if [ -f SMakefile.scala ] && [ "./$1" != "./SMakefile.scala" ]
then
    echo scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" -Xlint -nc SMakefile.scala $@
    scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" -Xlint -nc SMakefile.scala $@
else
    echo scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" -Xlint -nc $@
    scala -classpath "$TIME_JAR:$JODATIME_JAR:$JODAPRIM_JAR:$JODACONVERT_JAR:$SCALAMAKE_JAR" -Xlint -nc $@
fi
